/**
 * 语音记录类型定义
 * Voice Record Type Definitions
 */

export type VoiceRecordStatus = "recording" | "processing" | "completed" | "failed";
export type VoiceRecordType = "reminder" | "note" | "task" | "event" | "thought";

export interface VoiceRecord {
  id: string;
  type: VoiceRecordType;
  status: VoiceRecordStatus;
  
  // 音频相关
  audioUrl?: string; // 音频文件 URL
  duration: number; // 录音时长（秒）
  
  // 转录结果
  transcript?: string; // 语音转文字结果
  confidence?: number; // 识别置信度 0-100
  
  // 智能解析
  extractedInfo?: {
    entities?: Array<{
      type: "time" | "date" | "person" | "location" | "task" | "other";
      value: string;
      confidence: number;
    }>;
    intent?: string; // 意图识别
    sentiment?: "positive" | "neutral" | "negative"; // 情感分析
    keywords?: string[]; // 关键词提取
  };
  
  // 自动生成的提醒
  autoGeneratedReminder?: {
    reminderId: string;
    scheduledAt: string;
    title: string;
  };
  
  // 用户画像更新
  profileUpdates?: {
    dimension: string; // 更新的画像维度
    changes: Record<string, unknown>; // 具体变更
  };
  
  // 元数据
  createdAt: string;
  updatedAt: string;
  deviceInfo?: {
    platform: string;
    browser?: string;
  };
}

